//PEGANDO A DATA ENVIADO PELO FORMULÁRIO E COLOCANDO ELA NO MODELO DIA/MES/ANO
export default function arrumaData (dataForm) {
  //RECEBE A DATA DO FORMULÁRIO
  //SPLIT: SEPARA AS INORMAÇÕES DE DIA MES E ANO QUE VEM JUNTAS COM IFEM
  //REVERSE: ARRUMA AS INFORMAÇÕES QUE ESTAVA ANO DIA MES PARA DIA MES ANO
  //JOIN: REFAZ A STRING COM A SEPARAÇÃO POR IFEM NOVAMENTE AGORA NO FORMATO DIA-MES-ANO
  const dataNova = dataForm.split("-").reverse().join("/")
  //RETORNA A DATA NO FORMATO CORRETO PARA O BANCO DE DADOS
  return dataNova
}
